### ISSUE TITLE
Cannot run sample script from guide: ImportError: cannot import name 'Celery'

### ISSUE THREAD

**Issue by hollowbit** [celery/celery#5324]
# Checklist

- [ x ] I have included the contents of ``pip freeze`` in the issue.
- [ x ] I have verified that the issue exists against the `master` branch of Celery

## Environment & Settings
4.2.1 (windowlicker)

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.6.7
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: : Linux s4s 4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Python Packages

<details>
amqp==2.4.1
apturl==0.5.2
asn1crypto==0.24.0
billiard==3.5.0.5
Brlapi==0.6.6
celery==4.2.1
certifi==2018.1.18
chardet==3.0.4
command-not-found==0.3
cryptography==2.1.4
cupshelpers==1.0
defer==1.0.6
distro-info==0.18
httplib2==0.9.2
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
kombu==4.2.2.post1
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
librabbitmq==2.0.0
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
netifaces==0.10.4
oauth==1.0.1
olefile==0.45.1
pexpect==4.2.1
Pillow==5.1.0
protobuf==3.0.0
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyRFC3339==1.0
python-apt==1.6.2
python-debian==0.1.32
pytz==2018.9
pyxdg==0.25
PyYAML==3.12
redis==3.1.0
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
simplejson==3.13.2
six==1.12.0
system-service==0.3
systemd-python==234
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
usb-creator==0.3.3
vine==1.2.0
wadllib==1.3.2
xkit==0.0.0
zope.interface==4.3.2
</details>

### Other Dependencies

<details>
librabbitmq and redis
</details>

## Minimally Reproducible Test Case
I was simply following the guide on how to set up a simple project. I am using Python 3.6.7 and pip3.

<details>
1. Install celery and dependencies

```
pip3 install -U "Celery[librabbitmq,redis]"
```

2. Setup the code just like in the guide

```python
from celery import Celery

app = Celery('hello', broker='redis://localhost:6379/0')

@app.task
def hello():
    return 'hello world'
```

3. Run script

```
python3 celery.py
```

</details>

# Expected Behavior
I expected it to at least run past the first line.

# Actual Behavior

Fails with error.

```
Traceback (most recent call last):
  File "celery.py", line 1, in <module>
    from celery import Celery
  File "/home/nate/dicom/sandbox/celery/celery.py", line 1, in <module>
    from celery import Celery
ImportError: cannot import name 'Celery'
```

Does it not work in python 3.6.7? Are the instructions missing a step or making an assumption that I do not meet? Thanks!

**Comment by hollowbit** [comment]
Well, it turns out I needed to run it with the celery command, not with python directly...
```
celery -A tasks worker --loglevel=info
```
