### ISSUE TITLE
First Steps with Django docs AMQP Error

### ISSUE THREAD

**Issue by jdnier** [celery/celery#1477]
I'm going through the "First Steps with Django" docs (http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html) and can't get a worker started due to an "Unknown AMQP method" exception. This is on a clean pip install of django and django-celery on Ubuntu. Since this is an intro document and following the instructions under Ubuntu 13.04 fails, I am reporting it as a bug. (I'm also looking for a solution.) If this is a version mismatch between the components, some clarification on what's currently required would help new users.

After creating a new virtualenv (Python 2.7.4), "pip install django django-celery" installs the following versions:

```
django (1.5.1)
celery (3.0.21)
kombu (2.5.12)
django-celery (3.0.17)
```

I have upgraded to the latest RabbitMQ deb (3.1.3) from the RabbitMQ web site (Ubuntu 13.04's default is 3.0.2).

After following the set up instructions, starting a worker with

```
$ python manage.py celery worker --loglevel=info
```

fails with the following exception:

```
[2013-07-17 14:02:05,784: INFO/MainProcess] consumer: Connected to amqp://guest@127.0.0.1:5672//.
[2013-07-17 14:02:05,913: ERROR/MainProcess] Unrecoverable error: AMQPError('Unknown AMQP method (10, 60)', None, None, None, '')
Traceback (most recent call last):
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 369, in start
    component.start()
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 401, in start
    self.reset_connection()
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 759, in reset_connection
    self.reset_pidbox_node()
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 697, in reset_pidbox_node
    callback=self.on_control,
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 87, in listen
    consumer.consume()
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/kombu/messaging.py", line 445, in consume
    self._basic_consume(T, no_ack=no_ack, nowait=False)
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/kombu/messaging.py", line 568, in _basic_consume
    no_ack=no_ack, nowait=nowait)
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/kombu/entity.py", line 595, in consume
    nowait=nowait)
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/amqp/channel.py", line 1769, in basic_consume
    (60, 21),  # Channel.basic_consume_ok
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 69, in wait
    self.channel_id, allowed_methods)
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/amqp/connection.py", line 237, in _wait_method
    self.wait()
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 71, in wait
    return self.dispatch_method(method_sig, args, content)
  File "/home/dn/.virtualenvs/celery-env/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 85, in dispatch_method
    raise AMQPError('Unknown AMQP method %r' % (method_sig, ))
AMQPError: Unknown AMQP method (10, 60)
```

I have tried downgrading kombu as explained here: http://stackoverflow.com/a/15306234/234823
However, neither komu 2.4.7 nor 2.4.10 seem to work with Django 1.5; I end up with a new error,

```
ImportError: Could not import settings 'celerytest_project.settings' (Is it on sys.path?): cannot import name next
```

that goes away as soon a I restore kombu to the current version, 2.5.12.

I've tried upgrading kombu to current git hub (3.0.0a1). Alas it's broken.
