### ISSUE TITLE
chains + groups not working with json task serializer

### ISSUE THREAD

**Issue by zllak** [celery/celery#2076]
There seems to be a bug when doing "complex" chains/groups with the json task serializer.
First, I ran into celery/celery#2033.

Then, tried with simplejson, and got another problem.

This is what I'm doing:
````python
@app.task
def a(a):
    print("a: {0}".format(a))
    return 1

@app.task
def b(a):
    print("b: {0}".format(a))
    return 2

@app.task
def c(a):
    print("c: {0}".format(a))
    return 3

@app.task
def d():
    print("d")
    return 4

@app.task
def gl():
    gr = group(
        a.s(),
        b.s() | c.s(),
        b.s() | c.s()
    )
    return (d.si() | gr)()
````

I'm using Redis as both broker and result backend. If I change the TASK_SERIALIZER to pickle, everything runs as expected. With standard json lib, I got the "keys must be string" exception, and with simplejson, I got this:

````
[2014-06-05 15:01:31,953: WARNING/MainProcess] celery@thomas ready.
[2014-06-05 15:02:12,507: WARNING/Worker-5] d
[2014-06-05 15:02:12,530: WARNING/Worker-2] a: 4
[2014-06-05 15:02:12,530: ERROR/MainProcess] Task celery.group[fcf07257-7dc0-47cf-bfe2-ad9b836a7030] raised unexpected: AttributeError("'dict' object has no attribute '_merge'",)
Traceback (most recent call last):
  File "/home/zllak/venv/backend/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/zllak/venv/backend/local/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/zllak/venv/backend/local/lib/python2.7/site-packages/celery/app/builtins.py", line 165, in run
    add_to_parent=False) for stask in taskit]
  File "/home/zllak/venv/backend/local/lib/python2.7/site-packages/celery/app/builtins.py", line 157, in <genexpr>
    for i, task in enumerate(tasks))
  File "/home/zllak/venv/backend/local/lib/python2.7/site-packages/celery/canvas.py", line 192, in clone
    'immutable': self.immutable}, app=self._app)
  File "/home/zllak/venv/backend/local/lib/python2.7/site-packages/celery/canvas.py", line 135, in from_dict
    return self.TYPES[typ].from_dict(kwdict(d), app=app)
  File "/home/zllak/venv/backend/local/lib/python2.7/site-packages/celery/canvas.py", line 356, in from_dict
    tasks[0]['args'] = tasks[0]._merge(d['args'])[0]
AttributeError: 'dict' object has no attribute '_merge'
````

Exactly the same code, just with the TASK_SERIALIZER pickle:
````
[2014-06-05 15:05:01,559: WARNING/MainProcess] celery@thomas ready.
[2014-06-05 15:05:03,520: WARNING/Worker-2] d
[2014-06-05 15:05:03,532: WARNING/Worker-7] a: 4
[2014-06-05 15:05:03,532: WARNING/Worker-4] b: 4
[2014-06-05 15:05:03,533: WARNING/Worker-6] b: 4
[2014-06-05 15:05:03,545: WARNING/Worker-7] c: 2
[2014-06-05 15:05:03,545: WARNING/Worker-2] c: 2
````

**Comment by zllak** [comment]
Perfectly working on 3.1.17.
