### PR TITLE
Add support pymongo 3.12

### PR DESCRIPTION
**Pull request by kidoz**
## Description
Fixed problem with import `uri_parser` in pymongo 4.12.0.

After update from pymongo 4.11.3 to 4.12.0 catch error:
`Unrecoverable error: "AttributeError(\"module 'pymongo' has no attribute 'uri_parser'\")"`

In pymongo 4.12.0 done refactoring and current usage like `pymongo.uri_parser.parse_uri` no longer possible

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
Can you please pin your dependencies with exact version of celery? the latest version should drop python 3.8 support if I am not wrong. we should wait before moving with this.

**Comment by kidoz** [comment]
> Can you please pin your dependencies with exact version of celery? the latest version should drop python 3.8 support if I am not wrong. we should wait before moving with this.

Add [Poetry dependencies](https://github.com/user-attachments/files/19773315/dependencies.zip)

**Comment by auvipy** [comment]
> @auvipy
> 
> > the latest version should drop python 3.8 support if I am not wrong. we should wait before moving with this.
> 
> This change appears to fix a semantic issue. Why should we wait with it?

because it is relevant only when we upgrade to pymongo 4.12

After update from pymongo 4.11.3 to 4.12.0 catch error:
Unrecoverable error: "AttributeError(\"module 'pymongo' has no attribute 'uri_parser'\")"

File: celery/backends/mongodb.py [hunk 1]
```diff
@@ -20,6 +20,7 @@
         from bson.binary import Binary
     except ImportError:
         from pymongo.binary import Binary
+    from pymongo import uri_parser
```
[the remark this answers is not in the document]
Comment (auvipy) [reply celery/backends/mongodb.py:23]: yes we can try this

[the remark this answers is not in the document]
Comment (cjwatson) [reply celery/backends/mongodb.py:23]: The LLM slop is wasting your time here.  `from pymongo import uri_parser` is fine in both old and new versions.
