### ISSUE TITLE
Celery worker can't start on windows after update billiard to 3.5.0.0

### ISSUE THREAD

**Issue by rakhinskiy** [celery/celery#3414]
[2016-08-27 01:51:41,357: ERROR/MainProcess] Unrecoverable error: AttributeError("'module' object has no attribute 'CreateProc
ess'",)
Traceback (most recent call last):
  File "c:\tools\python\2.7\lib\site-packages\celery\worker\__init__.py", line 206, in start
    self.blueprint.start(self)
  File "c:\tools\python\2.7\lib\site-packages\celery\bootsteps.py", line 123, in start
    step.start(parent)
  File "c:\tools\python\2.7\lib\site-packages\celery\bootsteps.py", line 374, in start
    return self.obj.start()
  File "c:\tools\python\2.7\lib\site-packages\celery\concurrency\base.py", line 131, in start
    self.on_start()
  File "c:\tools\python\2.7\lib\site-packages\celery\concurrency\prefork.py", line 119, in on_start
    **self.options)
  File "c:\tools\python\2.7\lib\site-packages\billiard\pool.py", line 1015, in __init__
    self._create_worker_process(i)
  File "c:\tools\python\2.7\lib\site-packages\billiard\pool.py", line 1124, in _create_worker_process
    w.start()
  File "c:\tools\python\2.7\lib\site-packages\billiard\process.py", line 122, in start
    self._popen = self._Popen(self)
  File "c:\tools\python\2.7\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "c:\tools\python\2.7\lib\site-packages\billiard\popen_spawn_win32.py", line 54, in __init__
    hp, ht, pid, tid = _winapi.CreateProcess(
AttributeError: 'module' object has no attribute 'CreateProcess'

If downgrade billiard to 3.3.0.23 all work fine
I run celery by this command "celery -l info -A app worker -c1"
