### ISSUE TITLE
3.1.21 backend .as_uri() crash

### ISSUE THREAD

**Issue by kaidokert** [celery/celery#3094]
Celery workers wont start after upgrade from 3.1.20->3.1.21
Root cause seems to be @beb450be0de4030865c7fda621f4cbfc31876325

Error below:
```
[2016-03-05 10:16:58,763: ERROR/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'rstrip'",)
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/celery_test/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/celery_test/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    self.on_start()
  File "/home/ubuntu/.virtualenvs/celery_test/local/lib/python2.7/site-packages/celery/apps/worker.py", line 169, in on_start
    string(self.colored.cyan(' \n', self.startup_info())),
  File "/home/ubuntu/.virtualenvs/celery_test/local/lib/python2.7/site-packages/celery/apps/worker.py", line 230, in startup_info
    results=self.app.backend.as_uri(),
  File "/home/ubuntu/.virtualenvs/celery_test/local/lib/python2.7/site-packages/celery/backends/base.py", line 117, in as_uri
    else maybe_sanitize_url(self.url).rstrip("/"))
AttributeError: 'NoneType' object has no attribute 'rstrip'
```

**Comment by Lispython** [comment]
Confirm. I have too.

**Comment by thijstriemstra** [comment]
Just wasted a lot of time coming to the same conclusion.

**Comment by hakanw** [comment]
+1

**Comment by hakanw** [comment]
All my celery workers are failing on the latest stable version due to this, have to roll them back to the older version.

**Comment by mbande** [comment]
same error here

**Comment by ask** [comment]
This is already fixed in development, to confirm please test: `pip install -U https://github.com/celery/celery/zipball/3.1#egg=celery`

**Comment by ask** [comment]
3.1.22 released

**Comment by atomicopossum** [comment]
I'm still (with 3.1.22) having a similar issue with the mongodb backend. My initialization looks like
`celery_app = Celery('app', broker='pyampq://', backend='mongodb')`
and then I set the MongoDB connection information later with `celery_app.conf.update()`

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    self.on_start()
  File "/usr/lib/python2.7/site-packages/celery/apps/worker.py", line 169, in on_start
    string(self.colored.cyan(' \n', self.startup_info())),
  File "/usr/lib/python2.7/site-packages/celery/apps/worker.py", line 230, in startup_info
    results=self.app.backend.as_uri(),
  File "/usr/lib/python2.7/site-packages/celery/backends/mongodb.py", line 258, in as_uri
    if ',' not in self.url:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by ask** [comment]
@atomicopossum help! we are running out of version numbers, but 3.1.23 is out now
