### ISSUE TITLE
TypeError in make_connection, unexpected keyword argument 'socket_keepalive'

### ISSUE THREAD

**Issue by jaap3** [celery/celery#5994]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- #5952
- #2903

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.1

# Steps to Reproduce

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>
```
redis==3.4.1
billiard==3.6.3.0
celery==4.4.1
kombu==4.6.8
```
</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Celery just works

# Actual Behavior

After upgrading Celery from 4.4.0 to 4.4.1 I suddenly see `TypeError: __init__() got an unexpected keyword argument 'socket_keepalive'`.

This seems to be caused by PR #5952, which adds this kwarg for Redis connections. However, not all Redis connection constructors take the same arguments (e.g. `UnixDomainSocketConnection` doesn't take `socket_keepalive`). This seems to be happened before as noted in issue #2903.

Everything works fine if I downgrade to 4.4.0 again.

**Comment by auvipy** [comment]
can you check the commit log after 4.4.1 release? this might have already resolved in master?

**Comment by jaap3** [comment]
I did check the commit log (I also checked that option in the checklist). None of the (now) 4 commits since the release of 4.4.1 seem related to this issue.

I'm unable to test against master as the only place I can test this reliably is a production server. I was hoping Celery's tests would catch an issue like this, but it seems that the Travis pipeline is not running the integration tests.

**Comment by auvipy** [comment]
ops sorry to know that! thanks for letting us know! will try to push another minor release ASAP

**Comment by Seleznev-nvkz** [comment]
@jaap3 could you look on this PR https://github.com/celery/celery/pull/6000? For me, this change fixes the problem

**Comment by jaap3** [comment]
@Seleznev-nvkz and @auvipy thanks for the fix, looking forward to the next patch release ;)

**Comment by auvipy** [comment]
expect one tomorrow
