### ISSUE TITLE
Celery 4.3 result_extended doesn't push extended meta data to some backends when set to true

### ISSUE THREAD

**Issue by mrkcmo** [celery/celery#5436]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
celery -A celeryacl report

software -> celery:4.3.0 (rhubarb) kombu:4.5.0 py:3.6.8
billiard:3.6.0.0 py-amqp:2.4.2
platform -> system:Linux arch:64bit
kernel version:4.18.0-1013-azure imp:CPython
loader -> celery.loaders.app.AppLoader
settings -> transport:amqp results:db+mysql+pymysql://celery:**@X.X.X.X:XXXX/celeryresults
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
pip freeze
amqp==2.4.2
asn1crypto==0.24.0
bcrypt==3.1.6
billiard==3.6.0.0
celery==4.3.0
cffi==1.12.2
Click==7.0
cryptography==2.6.1
Flask==1.0.2
Flask-Cors==3.0.7
itsdangerous==1.1.0
Jinja2==2.10
kombu==4.5.0
MarkupSafe==1.1.1
mysql-connector-python==8.0.15
netmiko==2.3.3
paramiko==2.4.2
protobuf==3.7.1
pyasn1==0.4.5
pycparser==2.19
PyMySQL==0.9.3
PyNaCl==1.3.0
pyserial==3.4
pytz==2018.9
PyYAML==5.1
scp==0.13.2
six==1.12.0
SQLAlchemy==1.2.14
textfsm==0.4.1
vine==1.3.0
Werkzeug==0.15.2
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

With the following configured "result_extended" to true I expected to see more meta data in the backend results DB but I don't. I just see the standard results.

app = Celery('tasks',
             backend='db+mysql+pymysql://XXX:XXX@X.X.X.X:XXXX/celeryresults',
             broker='amqp://networkautomation:B2p2k6nb!@X.X.X.X/celery',
             result_extended=True)
# Actual Behavior

**Comment by mrkcmo** [comment]
celery -A celeryacl report

software -> celery:4.3.0 (rhubarb) kombu:4.5.0 py:3.6.8
            billiard:3.6.0.0 py-amqp:2.4.2
platform -> system:Linux arch:64bit
            kernel version:4.18.0-1013-azure imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:db+mysql+pymysql://celery:**@X.X.X.X:XXXX/celeryresults

**Comment by mrkcmo** [comment]
pip freeze
amqp==2.4.2
asn1crypto==0.24.0
bcrypt==3.1.6
billiard==3.6.0.0
celery==4.3.0
cffi==1.12.2
Click==7.0
cryptography==2.6.1
Flask==1.0.2
Flask-Cors==3.0.7
itsdangerous==1.1.0
Jinja2==2.10
kombu==4.5.0
MarkupSafe==1.1.1
mysql-connector-python==8.0.15
netmiko==2.3.3
paramiko==2.4.2
protobuf==3.7.1
pyasn1==0.4.5
pycparser==2.19
PyMySQL==0.9.3
PyNaCl==1.3.0
pyserial==3.4
pytz==2018.9
PyYAML==5.1
scp==0.13.2
six==1.12.0
SQLAlchemy==1.2.14
textfsm==0.4.1
vine==1.3.0
Werkzeug==0.15.2

**Comment by mrkcmo** [comment]
As referenced here: http://docs.celeryproject.org/en/latest/whatsnew-4.3.html#result-backends it doesn't state that any additional configuration is needed but perhaps I am missing something.

**Comment by mjmonroe** [comment]
I am seeing the same issue with the MongoDB result backend. The MongoDB backend overrides [`_store_result`](https://github.com/celery/celery/blob/a616ae7c02fa137de2250f66d0c8db693e070210/celery/backends/mongodb.py#L181) and does not call the base.py `_store_result` method. The base.py [`_store_result`](https://github.com/celery/celery/blob/a616ae7c02fa137de2250f66d0c8db693e070210/celery/backends/base.py#L699) method is where the code was changed to add the extended results.

Possible solutions include adding the new result_extended code to the `_store_result` method of the MongoDB backend, or having the backend call the super method and store those values in the database. I am not sure why `_store_result` was overridden, since MongoDB can act like a key/value store.

**Comment by thedrow** [comment]
Ok this should be a very easy fix.
Any volunteers for a PR?

**Comment by mdawar** [comment]
I don't know how much this is related, I'm using **Redis** as the broker and the result backend and I'm setting `result_extended` to `True` and everything is working fine except for the task name, when I try to access `task.name` it's always `None`, after debugging the `Context` object that is being passed to `BaseKeyValueStoreBackend.store_result` it contains the task name with the attribute `task` and not `task_name` as `BaseKeyValueStoreBackend._store_result` is trying to get from the request object:

```python
if self.app.conf.find_value_for_key('extended', 'result'):
    if request:
        request_meta = {
            'name': getattr(request, 'task_name', None),
            'args': getattr(request, 'args', None),
            'kwargs': getattr(request, 'kwargs', None),
            'worker': getattr(request, 'hostname', None),
            'retries': getattr(request, 'retries', None),
            'queue': request.delivery_info.get('routing_key')
            if hasattr(request, 'delivery_info') and
            request.delivery_info else None
        }

        meta.update(request_meta)
```

**Comment by thedrow** [comment]
@mdawar This is a different bug, please submit a new issue about it.

**Comment by mrkcmo** [comment]
> 
> 
> @mikolevy Thanks for the accurate analysis. We overlooked those.
> 
> This should be a very easy fix.
> Any volunteers for a PR?

@thedrow I am willing to give it a go unless someone who is more familiar with Celery is willing to step up.

**Comment by thedrow** [comment]
Go for it.

**Comment by mrkcmo** [comment]
@thedrow do I need contributor rights to create the branch with the fix? Also do you have some rules or guidelines on how to name the branch etc...?

**Comment by thedrow** [comment]
Create a fork and submit a pull request from a branch.
We don't care about the branch name since it's in your fork, you can do whatever you want in your fork.

I suggest that you read our CONTRIBUTING document.

**Comment by metatick** [comment]
I'm not sure if I'm missing something, but this issue also seems to affect:

AMQPBackend: store_result overridden, does not implement result_extended
CassandraBackend: _store_result overridden, does not implement result_extended
DatabaseBackend: _store_result overridden, does not implement result_extended
RPCBackend: store_result overridden, does not implement result_extended

Looks like every backend that doesn't extend KeyValueStoreBackend is at fault?

Perhaps it's worth refactoring so that all the standard message 'construction' (including result_extended) is within Backend.store_result(). 

Each implementation must implement _store_result() and never, ever override store_result().

Thoughts?

**Comment by thedrow** [comment]
You could simply create a private method which must be called in `store_result()` named `_maybe_extend_result(result)` which will add data as needed.

**Comment by mrkcmo** [comment]
You are outside of my capability on this one. If someone else wants to work on a more global solution I would be all for that.

**Comment by johnarnold** [comment]
I wrote the original PR, and didn't scope it to the other backends other than KV (redis for my use case). I don't see any reason it can't be generalized to all backends; however, someone would have to go update those backends that have overridden store_result()

**Comment by safwanrahman** [comment]
This should not be closed. @auvipy Can you please open it?

**Comment by auvipy** [comment]
this was auto closed by Github!!

**Comment by adamcohenhillel** [comment]
Still not working with celery v5.0.5

**Comment by thedrow** [comment]
> 
> 
> Still not working with celery v5.0.5

Feel free to contribute this functionality to other backends. Which ones have we missed?

**Comment by iegorval** [comment]
> > Still not working with celery v5.0.5
> 
> Feel free to contribute this functionality to other backends. Which ones have we missed?

Not sure what I am missing, but with Celery 5 and Redis I do not see any extended data in Flower despite setting `app.conf.result_extended=True` . Any ideas?
