### PR TITLE
fix AttributeError regression in #6619

### PR DESCRIPTION
**Pull request by fuhrysteve**
## Description

Fixes regression in #6619 

Please see the relevant stacktrace below:

```python
    def _evaluate_entry_args(entry_args):
        if not entry_args:
            return []                              
        return [
            v() if isinstance(v, BeatLazyFunc) else v
>           for v in entry_args.args                                                                                                                                                                         
        ]                         
E       AttributeError: 'tuple' object has no attribute 'args'
                                    
celery/beat.py:211: AttributeError
```

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
thanks!
