### ISSUE TITLE
Task fail to classmethod   in version 4.0.0

### ISSUE THREAD

**Issue by 631068264** [celery/celery#3609]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I use this command `celery -A base worker -Q mail_remind,sms_remind -l INFO`
```
class PushBullet(object):
    headers = config.PushBullet.headers
    phone_id = config.PushBullet.phone_id
    pc_id = config.PushBullet.pc_id
    push_url = config.PushBullet.push_url

    @classmethod
    @app.task
    def send_sms_to_phone(cls, title='', body='', device_iden=phone_id):
        if title or body:
            data = {
                "type": "note",
                "title": title,
                "body": body,
                "device_iden": device_iden
            }
           
           # This is requests.post
            post(cls.push_url, cls.headers, data)
```

And then I call it just like this

`PushBullet.send_sms_to_phone.apply_async(args=(title, body))`

and it raise an error. 
## Expected behavior

When I call it like this `PushBullet.send_sms_to_phone(title, body)` is OK.

## Actual behavior
```
[2016-11-19 11:24:27,591: ERROR/PoolWorker-6] Task base.sms_util.send_sms_to_phone[87afdb95-06b8-4eb4-bf52-91afa9913b2c] raised unexpected: AttributeError("'str' object has no attribute 'push_url'",)
Traceback (most recent call last):
  File "/Users/wyx/project/message/.env/lib/python3.5/site-packages/celery/app/trace.py", line 368, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/wyx/project/message/.env/lib/python3.5/site-packages/celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/wyx/project/message/base/sms_util.py", line 48, in send_sms_to_phone
    post(cls.push_url, cls.headers, data)
AttributeError: 'str' object has no attribute 'push_url'
```

**Comment by ask** [comment]
Did this work in 3.1?  I have a hard time seeing how this can work, considering that @app.task doesn't return a function, it returns a class instance that happens to be callable.

**Comment by dralley** [comment]
I came across this independently and didn't notice this issue.  I actually get an entirely different traceback, but the same results: classmethod tasks no longer work.

More info in #3863
