### ISSUE TITLE
current master broken ?

### ISSUE THREAD

**Issue by bastianh** [celery/celery#2954]
Hi,
I wanted to test if my project works with celery 4.0rc1 and tried the current master, but looks that I can't even `from celery import Celery`.

```
Python 3.4.3 (default, Sep 28 2015, 11:07:34)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from celery import Celery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bastianh/Development/tmp/celery/celery/celery/__init__.py", line 137, in <module>
    from celery import five  # noqa
  File "/Users/bastianh/Development/tmp/celery/celery/celery/five.py", line 21, in <module>
    from amqp.five import __all__ as _all_five
ImportError: cannot import name '__all__'
>>>
```

I just installed celery from git, following modules are installed:

```
$ pip freeze
amqp==1.4.8
anyjson==0.3.3
billiard==3.3.0.21
celery==4.0.0rc1
kombu==3.0.30
pytz==2015.7
wheel==0.24.0
```

**Comment by ask** [comment]
You also need to use master of kombu, amqp, and billiard:

    pip install -r requirements/dev.txt
