### ISSUE TITLE
5.3.2/3 has BREAKING change on EagerResult

### ISSUE THREAD

**Issue by benconnito** [celery/celery#8472]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [ ] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.3.3

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

a patch release to not have a breaking change

# Actual Behavior

https://github.com/celery/celery/commit/1c363876147325a196c474e757e355c451a0cdff#diff-05689f277021b9af9d8314849c9d938db0f5a42e932169a116463ef91ae9af78R986

```
TypeError
EagerResult.__init__() missing 1 required positional argument: 'state'
```

**Comment by ppfeufer** [comment]
Please yank the faulty versions from Pypi.

This is just the last 15 minutes since I updated from 5.3.1 to 5.3.3
![image](https://github.com/celery/celery/assets/2989985/5250b838-e998-4ddf-8c08-6eb4625dbd51)

**Comment by Nusnus** [comment]
Thank you for the report!

The last release seems to have created more than one issue so I'm still investigating what broke.

This situation should be dealt with by the end of the weekend.

**Comment by auvipy** [comment]
I am going to yank or delete both of the release for now

**Comment by KOliver94** [comment]
Hey guys,

Do you create `EagerResult` objects in your code and the problem is that the patch version introduced a breaking change or do you encounter this problem while using celery without custom functions?

Thanks!

**Comment by KOliver94** [comment]
@benconnito @ppfeufer can you help me if the only issue is the breaking change in the constructor for a patch version because you create `EagerResult` objects in your code or do you encounter this problem out-of-the-box?

**Comment by ppfeufer** [comment]
The TypeError exceptions happened in normal mode though, because none of our apps (or any app I know we use in our ecosystem) is using celery in eager mode in production.

**Comment by auvipy** [comment]
we got a proposed fix here https://github.com/celery/celery/pull/8486
