### ISSUE TITLE
Celery worker aborts without any message

### ISSUE THREAD

**Issue by jrief** [celery/celery#8310]
# Checklist
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

```
celery -A uniweb report

software -> celery:5.2.7 (dawn-chorus) kombu:5.3.0 py:3.9.17
            billiard:3.6.4.0 redis:4.5.4
platform -> system:Linux arch:64bit
            kernel version:3.10.0-1160.88.1.el7.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sentinel results:redis://:**@django-cms-test-redis-headless:6379/7
```

Our setup is Celery with Redis over Sentinel in a Kubernetes cluster. After upgrading Redis from version [4.5.4](https://github.com/redis/redis-py/releases/tag/v4.5.4) to 4.5.5 the Celery worker crashed without any message. Return code after crashing is 0.

The same image running on Docker-Swarm without Sentinel works flawlessly. 

pip freeze gives (I removed irrelevant packages):

```
billiard==3.6.4.0
…
django-redis==5.2.0
…
hiredis==2.2.3
…
kombu==5.3.0
…
redis==4.5.5  # <= the culprit, by downgrading to 4.5.4, Celery works fine
requests==2.31.0
…
urllib3==1.26.16
…
```

#8268 seems unrelated, because it has a different message.

**Comment by auvipy** [comment]
are you OK with https://github.com/celery/celery/pull/8317?

**Comment by sevdog** [comment]
What in redis is causing this crash? Is there an open issue on [redis-py](https://github.com/redis/redis-py/issues) which can help?

**Comment by sevdog** [comment]
This is because in my system with the following dependencies I am not experiencing any problem with the workers (but I am not yet using sentinel)

```
celery==5.2.7
kombu==5.2.4
redis==4.5.5
hiredis==2.2.3
```

Maybe there was a change in the 5.3 series of celery/kombu which caused this issue?

Do you have any DEBUG level logs regarding those crash you experienced?

**Comment by sevdog** [comment]
Found the problem:

```python
celery.worker - start - CRITICAL - Unrecoverable error: TypeError("SentinelManagedConnection.read_response() got an unexpected keyword argument 'disconnect_on_error'")
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/opt/venv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/opt/venv/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/opt/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/opt/venv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/opt/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/opt/venv/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/opt/venv/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/opt/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 1336, in on_readable
    self.cycle.on_readable(fileno)
  File "/opt/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 566, in on_readable
    chan.handlers[type]()
  File "/opt/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 910, in _receive
    ret.append(self._receive_one(c))
  File "/opt/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 920, in _receive_one
    response = c.parse_response()
  File "/opt/venv/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/opt/venv/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/opt/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/opt/venv/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/opt/venv/lib/python3.10/site-packages/redis/client.py", line 1540, in try_read
    return conn.read_response(disconnect_on_error=False)
TypeError: SentinelManagedConnection.read_response() got an unexpected keyword argument 'disconnect_on_error'
```

This was caused by https://github.com/redis/redis-py/commit/c0833f60a1d9ec85c589004aba6b6739e6298248 which changed how internally redis-py handles connection, unfortunatelly the Sentinel wrapper was not updated to reflect that change (see [`SentinelManagedConnection.read_response@4.5.5`](https://github.com/redis/redis-py/blob/v4.5.5/redis/sentinel.py#L56)).

The issue is fixed on the master branch in https://github.com/redis/redis-py/commit/35b7e09a57a1b7e2931d90e4b13858b68cee97cf
